export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_ERROR = "LIST_ERROR";

export const TOGGLE_MOVIE_IN_LIST_REQUEST = "TOGGLE_MOVIE_IN_LIST_REQUEST"
export const TOGGLE_MOVIE_IN_LIST_SUCCESS = "TOGGLE_MOVIE_IN_LIST_SUCCESS"
export const TOGGLE_MOVIE_IN_LIST_ERROR = "TOGGLE_MOVIE_IN_LIST_ERROR"