export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const FOLLOW_PROFILE = "FOLLOW_PROFILE";
export const UNFOLLOW_PROFILE = "UNFOLLOW_PROFILE";
export const FOLLOW_DONE = "FOLLOW_DONE";