# Generated by Django 3.1.4 on 2021-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20201226_1852"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["publish_on"]},
        ),
        migrations.AddField(
            model_name="movieratereview",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
