# Generated by Django 3.1.4 on 2021-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210114_2332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="contest",
        ),
        migrations.AddField(
            model_name="movie",
            name="contests",
            field=models.ManyToManyField(related_name="movies", to="api.Contest"),
        ),
    ]
