# Generated by Django 3.1.4 on 2021-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210117_1854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="api.Genre"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="mp_genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="api.MpGenre"
            ),
        ),
    ]
