# Generated by Django 3.1.4 on 2021-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210118_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="contests",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="api.Contest"
            ),
        ),
    ]
