# Generated by Django 3.1.4 on 2021-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20210123_1516"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="topcreator",
            unique_together={("contest", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="topcurator",
            unique_together={("contest", "profile")},
        ),
    ]
