# Generated by Django 3.1.4 on 2021-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20210123_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="topcreator",
            name="pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topcurator",
            name="pos",
            field=models.IntegerField(default=0),
        ),
    ]
