# Generated by Django 3.1.6 on 2021-03-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20210123_2125"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("S", "Short Film"), ("B", "Blog")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="movieratereview",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="api.movie",
            ),
        ),
    ]
