# Generated by Django 3.1.6 on 2021-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20210309_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="celeb_order",
            field=models.IntegerField(default=0),
        ),
    ]
