# Generated by Django 3.2.6 on 2021-08-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20210321_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[("C", "Created"), ("S", "Submitted"), ("R", "Rejected")],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.package",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contest",
            ),
        ),
        migrations.CreateModel(
            name="MovieOrderTemp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.movie",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.package",
                    ),
                ),
            ],
        ),
    ]
