# Generated by Django 3.2.6 on 2021-08-07 04:57

from django.db import migrations


def load_movie_order(apps, schema_editor):
    MovieOrderTemp = apps.get_model("api", "MovieOrderTemp")
    for obj in MovieOrderTemp.objects.all():
        order = obj.order
        if order:
            order.movies.add(obj.movie)
            order.package = obj.package
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20210807_1027"),
    ]

    operations = [
        migrations.RunPython(load_movie_order),
    ]
