# Generated by Django 3.2.16 on 2023-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20210810_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_thumb",
            field=models.URLField(blank=True, null=True),
        ),
    ]
